version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/urpg-server-1.0-SNAPSHOT.jar
    - appspec.yml
    - pipeline/onApplicationStop.sh
    - pipeline/onApplicationStart.sh
    - pipeline/onAfterInstall.sh
  discard-paths: yes